import type { Metadata } from 'next'
import { Fira_Code } from 'next/font/google'
import './globals.css'
import Footer from '@/components/footer'
import Navigation from '@/components/navigation'

const firaCode = Fira_Code({
  variable: '--font-fira-code',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${firaCode.variable} antialiased min-h-screen flex flex-col`}
      >
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  )
}
